import { Inter } from "next/font/google";
import "./globals.css";
import Welcome from "@/components/global/Welcome";
import TopLocationBar from "@/components/global/TobLocationBar";
import Search from "@/components/global/Search";
import NavigationBar from "@/components/global/NavigationBar";
import Footer from "@/components/global/Footer";
import LastFooter from "@/components/global/LastFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Best Electronic in Bangladesh",
  description: "Generated by Best Electronics",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Welcome />
        <TopLocationBar />
        <Search />
        <NavigationBar />
        
        
        {children}
        <Footer />
        <LastFooter />
      </body>
    </html>
  );
}
